### ISSUE TITLE
 unit testing

### ISSUE THREAD

**Issue by pepezane** [MPHETamines/MPHETamines#63]

**Comment by maphuti** [comment]
How far are we with this?

**Comment by Potlake** [comment]
Im still working on it, nothing works properly so far.

On Fri, Sep 11, 2015 at 7:30 AM, Maphuti H. Setati <notifications@github.com

**Comment by Potlake** [comment]
Im using karma and grunt for the unit testing, grunt is also working for integration test.

**Comment by pepezane** [comment]
martha can you commit the unit tests to github for marking please?
